swagger: "2.0"
info:
  version: 2.0.0
  title: Test
basePath: /api
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths: 
  /test:
    post:
      operationId: testPostReader
      parameters:
        - in: query
          name: aDate
          type: string
          format: datetime
        - in: body 
          name: payload 
          schema: 
            type: string 
            format: binary
      responses:
        "200":
          description: the version of the invoked instance
          schema:
            type: string