// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// TestPostReaderOKCode is the HTTP code returned for type TestPostReaderOK
const TestPostReaderOKCode int = 200

/*
TestPostReaderOK the version of the invoked instance

swagger:response testPostReaderOK
*/
type TestPostReaderOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewTestPostReaderOK creates TestPostReaderOK with default headers values
func NewTestPostReaderOK() *TestPostReaderOK {

	return &TestPostReaderOK{}
}

// WithPayload adds the payload to the test post reader o k response
func (o *TestPostReaderOK) WithPayload(payload string) *TestPostReaderOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the test post reader o k response
func (o *TestPostReaderOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TestPostReaderOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
