// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Test
//
//	Schemes:
//	  http
//	  https
//	Host: localhost
//	BasePath: /api
//	Version: 2.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
